AWSTemplateFormatVersion: '2010-09-09'
Description: Security Group allowing HTTP

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  SecurityGroupId:
    Value: !Ref WebSecurityGroup